version: '3'

services:
  db:
    image: postgres:17
    container_name: app-samples-db
    ports:
      - 5432:5432
    volumes:
      - postgres-17:/var/lib/postgresql/data
      - ./initdb.d:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

volumes:
  postgres-17:

# docker compose up -d
# docker compose down

# docker container prune --force
# docker volume rm app-samples_postgres-17
